/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in normal development and kept here so TypeScript can run in CI from a clean scaffold.
